### ISSUE TITLE
abapGit: diffs after installing

### ISSUE THREAD

**Issue by larshp** [fidley/FALV_abapgit#2]
I get some diffs after installing on a clean system, will take a look and try to fix in abapGit when I get some time,

![image](https://cloud.githubusercontent.com/assets/5888506/21528292/cd309c6a-cd31-11e6-9b97-49ff62703abe.png)

**Comment by fidley** [comment]
Thanks Lars, seems again it's something connected to GUI status.

**Comment by larshp** [comment]
texpool and CUA fixed, use latest abapGit version to install FALV

**Comment by fidley** [comment]
Brilliant @larshp ! Thanks

**Comment by larshp** [comment]
I've tested in 2 different systems on 2 different versions, so it seems to work.

However there are so many possibilities/tweaks in ABAP so there is most likely a new scenario that does not work 😄

**Comment by fidley** [comment]
It's there same with SAPlink, but anyway without such tools it would be really nasty to share ABAP stuff. Great job Lars.

**Comment by larshp** [comment]
Hope you like it, just if you have any suggestions/comments/find any errors just open an issue in the abapGit repository 😄
